export const exampleProfessionals = [
  {
    id: 'g1',
    name: 'María Gómez',
    category: 'Gasista',
    specialization: 'Instalación y reparación de estufas',
    rating: 4.8,
    reviewCount: 124,
    hourlyRate: 3500,
    distanceKm: 3.2,
    isVerified: true,
    description:
      'Técnica matriculada con 10 años de experiencia en calefacción doméstica.',
    imageUrl: 'https://i.pravatar.cc/150?img=1',
    badges: ['Matriculado', 'Urgencias 24hs'],
  },
  {
    id: 'g2',
    name: 'Juan Pablo Ríos',
    category: 'Gasista',
    specialization: 'Reparación de fugas y mantenimiento',
    rating: 4.6,
    reviewCount: 86,
    hourlyRate: 3000,
    distanceKm: 7.4,
    isVerified: false,
    description: 'Rápido diagnóstico y reparación de instalaciones domésticas.',
    imageUrl: 'https://i.pravatar.cc/150?img=2',
    badges: ['Garantía 3 meses'],
  },
  {
    id: 'g3',
    name: 'Lucía Fernández',
    category: 'Gasista',
    specialization: 'Instalación de calefacción central',
    rating: 4.9,
    reviewCount: 210,
    hourlyRate: 4200,
    distanceKm: 1.1,
    isVerified: true,
    description:
      'Especialista en sistemas centrales y proyectos residenciales.',
    imageUrl: 'https://i.pravatar.cc/150?img=3',
    badges: ['Matriculado', 'Proyectos'],
  },
  {
    id: 'g4',
    name: 'Carlos Méndez',
    category: 'Gasista',
    specialization: 'Instalación de termotanques',
    rating: 4.4,
    reviewCount: 42,
    hourlyRate: 2800,
    distanceKm: 4.7,
    isVerified: false,
    description: 'Atención rápida y precios competitivos en zona norte.',
    imageUrl: 'https://i.pravatar.cc/150?img=4',
    badges: ['Atención rápida'],
  },
  {
    id: 'g5',
    name: 'Ana Belén Suárez',
    category: 'Gasista',
    specialization: 'Instalación de estufas a gas',
    rating: 4.7,
    reviewCount: 95,
    hourlyRate: 3600,
    distanceKm: 2.6,
    isVerified: true,
    description: 'Tareas de instalación certificadas y revisiones preventivas.',
    imageUrl: 'https://i.pravatar.cc/150?img=5',
    badges: ['Matriculado', 'Garantía 6 meses'],
  },
  {
    id: 'g6',
    name: 'Fernando Ortega',
    category: 'Gasista',
    specialization: 'Emergencias y reparaciones',
    rating: 4.3,
    reviewCount: 58,
    hourlyRate: 4000,
    distanceKm: 9.0,
    isVerified: false,
    description: 'Servicio de urgencia 24/7 para reparaciones críticas.',
    imageUrl: 'https://i.pravatar.cc/150?img=6',
    badges: ['Urgencias 24hs'],
  },
];
